const KEY = "alisons-complete-v1";
const CAP = 4000;
const PAGE = 8;
const MARK = `<svg class="mark" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M5 20 L12 4 L19 20" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round"/><path d="M8.2 13.4 H15.8" stroke="currentColor" stroke-width="1.5"/></svg>`;
const PEOPLE = {
  me:    { id:"me",    name:"You",           initials:"YO", status:"In the room",   online:true },
  nara:  { id:"nara",  name:"Nara Okonkwo",  initials:"NO", status:"In the studio", online:true },
  lev:   { id:"lev",   name:"Lev Hartmann",  initials:"LH", status:"On a train",    online:true },
  mira:  { id:"mira",  name:"Mira Chen",     initials:"MC", status:"Deep work",     online:false },
  alice: { id:"alice", name:"Alice",         initials:"AL", status:"Guest",         online:true },
};
const REPLIES = ["Heard.","Keep going.","That lands.","Yes. One room.","Ship it while it's warm.","I'm in."];
function clock() { return new Date().toLocaleTimeString([], { hour:"2-digit", minute:"2-digit" }); }
function seedOlder(convId, authorId, n) {
  const out = [];
  for (let i = n; i >= 1; i--) out.push({ id:`old-${convId}-${i}`, convId, authorId, text:`Earlier note ${n-i+1} — the thread goes back further than fifty.`, at:"Mon", kind:"text", older:true });
  return out;
}
function defaults() {
  const rooms = [
    { id:"studio", name:"Studio", kind:"group", preview:"Nara: the object has to fit in one hand", time:"2m", unread:2, encrypted:true, alice:true, muted:false, members:["me","nara","lev","mira","alice"] },
    { id:"nara", name:"Nara Okonkwo", kind:"dm", preview:"Ship the feeling before the protocol", time:"11m", unread:0, encrypted:true, alice:false, muted:false, members:["me","nara"] },
    { id:"ops", name:"Ops", kind:"group", preview:"You: pagination is the honest bug", time:"1h", unread:0, encrypted:false, alice:false, muted:false, members:["me","lev","mira"] },
    { id:"mira", name:"Mira Chen", kind:"dm", preview:"Hold cannot touch PRIVATE rooms", time:"Yesterday", unread:0, encrypted:true, alice:false, muted:false, members:["me","mira"] },
  ];
  const messages = [
    ...seedOlder("studio","nara",12),
    { id:"s1", convId:"studio", authorId:"system", text:"Studio · private · Alice joined", at:"09:12", kind:"system" },
    { id:"s2", convId:"studio", authorId:"nara", text:"This has to be a room you would put your life in. Not a left-nav of apps.", at:"09:14" },
    { id:"s3", convId:"studio", authorId:"lev", text:"Direct, groups, presence, search, files. Calls next.", at:"09:16", reactions:[{glyph:"→", n:2, mine:true}] },
    { id:"s4", convId:"studio", authorId:"me", text:"Keep the wire. Change the object.", at:"09:17", mine:true },
    { id:"s5", convId:"studio", authorId:"alice", text:"I can see this room from join. I cannot see Nara's DMs. Remove me and I lose the thread.", at:"09:18" },
    { id:"s6", convId:"studio", authorId:"mira", text:"If counsel needs hold, that is a different mode.", at:"09:21", replyTo:"s5" },
    { id:"s7", convId:"studio", authorId:"nara", text:"The object has to fit in one hand.", at:"09:24" },
    { id:"n1", convId:"nara", authorId:"nara", text:"Ship the feeling. People do not fall in love with the protocol.", at:"08:40" },
    { id:"n2", convId:"nara", authorId:"me", text:"Then this surface is the argument.", at:"08:41", mine:true, edited:true },
    { id:"o1", convId:"ops", authorId:"lev", text:"History has to page. Fifty messages is not a product.", at:"Yesterday" },
    { id:"o2", convId:"ops", authorId:"me", text:"Pagination is the honest bug.", at:"Yesterday", mine:true },
    { id:"m1", convId:"mira", authorId:"mira", text:"Legal hold cannot touch PRIVATE rooms.", at:"Yesterday" },
  ];
  return { roomId:"studio", rooms, messages, profile:{ name:"You", status:"In the room" }, blocked:[], view:"room", spec:"features", pageOffset:{}, offline:false, outbox:[], notices:[{id:"n1", text:"Alice joined Studio", at:"09:12"}] };
}
function load() { try { const raw = localStorage.getItem(KEY); if (!raw) return defaults(); return { ...defaults(), ...JSON.parse(raw) }; } catch { return defaults(); } }
const S = { ...load(), draft:"", replyTo:null, overlay:null, query:"", mobile:"list", typing:null, muted:false, calling:false, elapsed:0, editing:null };
function persist() { localStorage.setItem(KEY, JSON.stringify({ roomId:S.roomId, rooms:S.rooms, messages:S.messages, profile:S.profile, blocked:S.blocked, view:S.view, spec:S.spec, pageOffset:S.pageOffset, offline:S.offline, outbox:S.outbox, notices:S.notices })); }
function person(id) { return PEOPLE[id]; }
function room() { return S.rooms.find(r => r.id === S.roomId) || S.rooms[0]; }
function threadAll() { return S.messages.filter(m => m.convId === S.roomId && !m.deleted); }
function visibleThread() { const all = threadAll(); const extra = S.pageOffset[S.roomId] || 0; const recent = all.filter(m => !m.older); const older = all.filter(m => m.older); return { olderLeft: Math.max(0, older.length - extra), items: [...older.slice(Math.max(0, older.length - extra)), ...recent] }; }
function esc(s) { return String(s ?? "").replace(/[&<>"']/g, c => ({ "&":"&","<":"<",">":">",'"':""","'":"&#39;" }[c])); }
function linkify(text) { return esc(text).replace(/(https?:\/\/[^\s<]+)/g, '<a href="$1" target="_blank" rel="noopener noreferrer">$1</a>'); }
function setRoom(id) { S.roomId = id; S.mobile = "thread"; S.overlay = null; S.rooms = S.rooms.map(r => r.id === id ? { ...r, unread:0 } : r); persist(); render(); queueMicrotask(() => document.getElementById("end")?.scrollIntoView({ block:"end" })); }
function send(override, kind="text") {
  const text = (override ?? S.draft).trim(); if (!text || text.length > CAP) return;
  if (S.offline) { S.outbox.push({ text, kind, roomId:S.roomId, replyTo:S.replyTo }); S.draft=""; S.replyTo=null; persist(); render(); return; }
  S.messages.push({ id:"m"+Date.now(), convId:S.roomId, authorId:"me", text, at:clock(), mine:true, replyTo:S.replyTo || undefined, kind });
  S.rooms = S.rooms.map(r => r.id === S.roomId ? { ...r, preview:`You: ${text}`, time:"Now", unread:0 } : r);
  S.draft=""; S.replyTo=null; persist(); render(); scheduleReply(S.roomId);
  queueMicrotask(() => document.getElementById("end")?.scrollIntoView({ block:"end" }));
}
function scheduleReply(roomId) {
  const r = S.rooms.find(x => x.id === roomId);
  const other = (r?.members || []).find(id => id !== "me" && id !== "alice" && !S.blocked.includes(id)) || (r?.members || []).find(id => id !== "me");
  if (!other) return;
  setTimeout(() => { if (S.roomId === roomId) { S.typing = other; render(); } }, 500);
  setTimeout(() => {
    const text = REPLIES[Math.floor(Math.random()*REPLIES.length)];
    S.typing = null;
    S.messages.push({ id:"r"+Date.now(), convId:roomId, authorId:other, text, at:clock() });
    S.rooms = S.rooms.map(rm => rm.id === roomId ? { ...rm, preview:text, time:"Now", unread: S.roomId===roomId ? 0 : rm.unread+1 } : rm);
    S.notices.unshift({ id:"nt"+Date.now(), text:`${person(other)?.name || "Someone"}: ${text}`, at:clock() });
    persist(); render();
  }, 1400);
}
function react(id) { S.messages = S.messages.map(m => { if (m.id !== id) return m; const cur = m.reactions || []; const mine = cur.find(r => r.mine); if (mine) return { ...m, reactions: cur.map(r => r.mine ? { ...r, n:r.n-1, mine:false } : r).filter(r => r.n>0) }; return { ...m, reactions: [...cur, { glyph:"→", n:1, mine:true }] }; }); persist(); render(); }
function delMsg(id) { S.messages = S.messages.map(m => m.id === id && m.mine ? { ...m, deleted:true, text:"" } : m); persist(); render(); }
function saveEdit(id, text) { const t = text.trim(); if (!t) return; S.messages = S.messages.map(m => m.id === id ? { ...m, text:t, edited:true } : m); S.editing = null; persist(); render(); }
function openDm(id) { let r = S.rooms.find(x => x.id === id); if (!r) { r = { id, name: person(id)?.name||id, kind:"dm", preview:"New conversation", time:"Now", unread:0, encrypted:true, alice:false, muted:false, members:["me", id] }; S.rooms = [r, ...S.rooms]; } setRoom(id); }
function toggleAlice() { const r = room(); const on = !!r.alice; S.rooms = S.rooms.map(x => x.id !== r.id ? x : { ...x, alice:!on, members: on ? x.members.filter(id => id !== "alice") : Array.from(new Set([...x.members, "alice"])) }); S.messages.push({ id:"sys"+Date.now(), convId:r.id, authorId:"system", text: on ? "Alice left the room" : "Alice joined the room", at:clock(), kind:"system" }); persist(); S.overlay = null; render(); }
function flushOutbox() { const items = S.outbox.splice(0); items.forEach(it => { S.roomId = it.roomId; S.replyTo = it.replyTo; S.draft = it.text; send(it.text, it.kind); }); }
const FEATURES = [["F-MSG","Real-time text","shipped","Socket rooms + persist."],["F-DM","Direct conversations","shipped","Idempotent createDirect."],["F-GRP","Groups","shipped","Rename, add, leave, transfer."],["F-PAGE","History pagination","hygiene","This model pages. Chat.tsx does not."],["F-CALL","Voice and video","stub","Icons. No TURN."],["F-ALICE","Visible AI guest","parked","Admit, disclose, remove."],["F-E2EE","MLS encryption","parked","Not Signal-on-MySQL."]];
const FIXES = [["H-9","Paginate past 50","API ready. Client never pages."],["GOD","Split Chat.tsx","81 KB. Extract before calls."],["ADMIN-UI","Give S-18 a screen","tRPC exists. This model has /admin."]];
const BLOCKERS = [["B-TURN","No STUN/TURN","Calls cannot ship without a relay."],["B-CRYPTO","E2EE is a re-architecture","MLS, devices, event log."],["B-LEGAL","Zero product legal","MIT is not a privacy policy."]];
function render() { const app = document.getElementById("app"); app.innerHTML = S.view === "spec" ? specView() : roomView(); bind(); }
function roomView() { const r = room(); return `<div class="banner ${S.offline ? "on":""}"><span>Offline. ${S.outbox.length} in the outbox.</span><button type="button" data-act="online">Go online</button></div><div class="shell" style="position:relative"><aside class="inbox" style="${S.mobile==="list"?"":"display:none"}">${inboxHtml()}</aside><section class="thread" style="${S.mobile==="thread"?"":"display:none"}">${threadHtml(r)}</section><aside class="inspect only-lg">${inspectHtml(r)}</aside>${S.overlay ? overlayHtml(r) : ""}</div>`; }
function inboxHtml() { return `<div class="top"><div class="brand">${MARK} Alisons</div><div><button class="icon" type="button" data-act="overlay" data-arg="compose" aria-label="New">${ico("plus")}</button><button class="icon" type="button" data-act="overlay" data-arg="notices" aria-label="Activity">${ico("bell")}</button><button class="icon" type="button" data-act="overlay" data-arg="settings" aria-label="Settings">${ico("gear")}</button></div></div><div class="rooms">${S.rooms.map(r => `<button class="room ${r.id===S.roomId?"on":""}" type="button" data-act="room" data-arg="${r.id}">${avatar(r)}<span class="meta"><span class="row"><span class="name">${esc(r.name)}</span><span class="time">${esc(r.time)}</span></span><span class="prev">${esc(r.preview)}</span></span>${r.unread>0?`<span class="pill">${r.unread}</span>`:""}</button>`).join("")}</div>`; }
function avatar(r) { if (r.alice || r.id === "alice") return `<span class="avatar alice">${MARK}</span>`; const p = person(r.id); const live = p?.online || (r.members||[]).some(id => id!=="me" && person(id)?.online); return `<span class="avatar">${esc((r.name||"?").slice(0,2).toUpperCase())}${live?`<span class="dot"></span>`:""}</span>`; }
function threadHtml(r) { const vis = visibleThread(); const online = (r.members||[]).some(id => id!=="me" && person(id)?.online); return `<header class="th"><button class="icon hidden-md" type="button" data-act="back" aria-label="Back">${ico("back")}</button>${avatar(r)}<div class="who"><p>${esc(r.name)}</p><span>${online?"Active now":"Away"}${r.alice?" · Alice in the room":""}${r.muted?" · muted":""}</span></div><button class="icon" type="button" data-act="overlay" data-arg="search" aria-label="Search">${ico("search")}</button><button class="icon" type="button" data-act="overlay" data-arg="media" aria-label="Files">${ico("file")}</button><button class="icon" type="button" data-act="call" aria-label="Call">${ico("phone")}</button><button class="icon hidden-lg" type="button" data-act="overlay" data-arg="people" aria-label="People">${ico("users")}</button></header><div class="feed" id="feed"><div class="feed-in">${vis.olderLeft ? `<button class="load-older" type="button" data-act="older">Load ${Math.min(PAGE, vis.olderLeft)} earlier</button>` : (threadAll().some(m=>m.older)?`<p class="sys">Beginning of room</p>`:"")}${vis.items.map(bubbleHtml).join("")}${S.typing ? `<p class="typing">${esc(person(S.typing)?.name||"Someone")} is writing…</p>`:""}<div id="end"></div></div></div><div class="comp"><div class="comp-in">${S.replyTo ? `<div class="replybar"><span>Replying · ${esc(S.messages.find(m=>m.id===S.replyTo)?.text||"")}</span><button type="button" data-act="noreply" aria-label="Cancel">✕</button></div>`:""}<div class="box"><button class="icon" type="button" data-act="attach" aria-label="Attach">${ico("clip")}</button><button class="icon" type="button" data-act="voice" aria-label="Voice">${ico("mic")}</button><textarea id="draft" rows="1" maxlength="${CAP}" placeholder="Message" aria-label="Message">${esc(S.draft)}</textarea><button class="send" type="button" data-act="send" ${S.draft.trim()?"":"disabled"}>Send</button></div><div class="count">${S.draft.length}/${CAP}</div></div></div>`; }
function bubbleHtml(m) { if (m.kind === "system") return `<p class="sys">${esc(m.text)}</p>`; if (m.deleted) return `<p class="sys">Message deleted</p>`; const who = person(m.authorId); const quoted = m.replyTo ? S.messages.find(x => x.id === m.replyTo) : null; const mine = !!m.mine; if (S.editing === m.id) return `<article class="bubble ${mine?"mine":""}"><textarea id="editbox" style="width:min(28rem,80vw);min-height:72px;background:var(--raised);border-radius:12px;padding:8px;border:1px solid var(--border)">${esc(m.text)}</textarea><div class="acts"><button type="button" data-act="saveedit" data-arg="${m.id}">Save</button><button type="button" data-act="canceledit">Cancel</button></div></article>`; const body = m.kind==="file" ? `<span class="filechip">${ico("file")} ${esc(m.text)}</span>` : m.kind==="voice" ? `<span class="filechip">${ico("mic")} ${esc(m.text)}</span>` : linkify(m.text); return `<article class="bubble ${mine?"mine":""}">${mine?"":`<p class="author">${esc(who?.name||"Unknown")}</p>`}<div class="body">${quoted?`<p class="quote">${esc(quoted.text)}</p>`:""}${body}${m.edited?`<span style="opacity:.6;font-size:12px"> edited</span>`:""}</div><div class="acts"><time>${esc(m.at)}</time><button type="button" data-act="reply" data-arg="${m.id}">Reply</button><button type="button" data-act="react" data-arg="${m.id}">Mark</button>${mine?`<button type="button" data-act="edit" data-arg="${m.id}">Edit</button><button type="button" data-act="del" data-arg="${m.id}">Delete</button>`:""}${(m.reactions||[]).map(rx=>`<span class="rx">${esc(rx.glyph)} ${rx.n}</span>`).join("")}</div></article>`; }
function inspectHtml(r) { const members = (r.members||[]).map(person).filter(Boolean); return `<div class="insp-h"><p class="k">ROOM</p><h2>${esc(r.name)}</h2><p class="tiny">${r.kind==="group"?"Group":"Direct"} · ${members.length} people · ${r.encrypted?"Private":"Shared host"}</p></div><div class="cardish"><div>${r.encrypted?"Only people in this room. Devices stay yours.":"Ops is on the current stack. Treat it as dogfood."}</div><button class="full" type="button" data-act="call">Call</button><button class="full" type="button" data-act="mute" style="background:var(--raised);color:var(--fg);margin-top:8px">${r.muted?"Unmute":"Mute"}</button></div><div class="plist"><p class="k">PEOPLE</p>${members.map(p => `<div class="person"><span class="avatar ${p.id==="alice"?"alice":""}">${p.id==="alice"?MARK:esc(p.initials)}${p.online?`<span class="dot"></span>`:""}</span><span><span style="display:block;font-size:14px">${esc(p.name)}</span><span class="tiny">${esc(p.status)}</span></span></div>`).join("")}${r.kind==="group"?`<button class="ghost" type="button" data-act="overlay" data-arg="alice">${r.alice?"Alice is a guest. Open her terms.":"Admit Alice as a guest."}</button>`:""}<button class="ghost" type="button" data-act="overlay" data-arg="admin">Owner tools</button></div>`; }
function overlayHtml(r) { const title = { search:"Search", contacts:"People", settings:"Settings", call:r.name, media:"Files", alice:"Alice", people:"Room", compose:"New", notices:"Activity", admin:"Owner" }[S.overlay] || S.overlay; return `<div class="mask" data-act="${S.overlay==="call"?"endcall":"close"}"><div class="dlg" role="dialog" aria-label="${esc(title)}" onclick="event.stopPropagation()"><div class="dlg-h"><h2>${esc(title)}</h2><button class="icon" type="button" data-act="${S.overlay==="call"?"endcall":"close"}" aria-label="Close">✕</button></div><div style="overflow:auto;min-height:0;flex:1">${overlayBody(r)}</div></div></div>`; }
function overlayBody(r) {
  if (S.overlay === "search") { const q = S.query.trim().toLowerCase(); const hits = q.length<2 ? [] : S.messages.filter(m => m.convId===S.roomId && !m.deleted && (m.text||"").toLowerCase().includes(q)); return `<input class="search" id="q" value="${esc(S.query)}" placeholder="Search ${esc(r.name)}" />${hits.map(h=>`<div class="hit"><p class="k">${esc(person(h.authorId)?.name||"")}</p>${esc(h.text)}</div>`).join("")}${q.length>=2 && !hits.length ? `<p class="tiny" style="padding:24px;text-align:center">Nothing in this room.</p>`:""}`; }
  if (S.overlay === "compose" || S.overlay === "contacts") { const people = Object.values(PEOPLE).filter(p => p.id!=="me" && !S.blocked.includes(p.id)); return `<p class="tiny" style="margin-bottom:12px">Message someone, or start a group.</p>${people.map(p=>`<div class="listbtn"><span class="avatar ${p.id==="alice"?"alice":""}">${p.id==="alice"?MARK:esc(p.initials)}</span><span style="flex:1"><span style="display:block">${esc(p.name)}</span><span class="tiny">${esc(p.status)}</span></span><button type="button" data-act="dm" data-arg="${p.id}" style="border-radius:999px;background:var(--raised);padding:6px 12px;font-size:12px">Message</button>${p.id!=="alice"?`<button type="button" class="tiny danger" data-act="block" data-arg="${p.id}">Block</button>`:""}</div>`).join("")}<button class="full" type="button" data-act="newgroup" style="margin-top:16px">New group · Studio West</button>`; }
  if (S.overlay === "settings") return `<label class="field"><span>Display name</span><input id="pname" value="${esc(S.profile.name)}" /></label><label class="field"><span>Status</span><input id="pstat" value="${esc(S.profile.status)}" /></label><button class="full" type="button" data-act="saveprofile">Save profile</button><p style="margin-top:20px"><button type="button" data-act="spec" class="tiny" style="text-decoration:underline">Internal spec</button></p><p><button type="button" data-act="offline" class="tiny">${S.offline?"Already offline":"Simulate disconnect"}</button></p><p><button type="button" data-act="export" class="tiny">Export this room</button></p><p><button type="button" data-act="reset" class="tiny danger">Sign out everywhere</button></p>`;
  if (S.overlay === "call") { const mm = String(Math.floor(S.elapsed/60)).padStart(2,"0"); const ss = String(S.elapsed%60).padStart(2,"0"); return `<div class="call"><div class="big">${MARK}</div><div style="text-align:center"><p style="font-family:var(--display);font-size:28px;margin:0">${esc(r.name)}</p><p class="tiny" style="font-variant-numeric:tabular-nums">${mm}:${ss} · preview · no media plane</p></div><div style="display:flex;gap:12px"><button class="icon" style="background:${S.muted?"var(--primary)":"var(--raised)"};color:${S.muted?"var(--on-primary)":"var(--muted)"}" type="button" data-act="mic">${ico("mic")}</button><span class="icon" style="background:var(--raised);color:var(--muted)">${ico("video")}</span><button class="hang" type="button" data-act="endcall" aria-label="End">${ico("phone")}</button></div></div>`; }
  if (S.overlay === "media") { const media = S.messages.filter(m => m.convId===S.roomId && (m.kind==="file"||m.kind==="voice")); if (!media.length) return `<p class="tiny" style="padding:40px;text-align:center">Nothing shared yet.</p>`; return media.map(m=>`<div class="hit">${m.kind==="voice"?ico("mic"):ico("file")} ${esc(m.text)}</div>`).join(""); }
  if (S.overlay === "alice") return `<div class="lede"><p style="color:var(--fg)">Alice is a visible participant. She is never a backend observer.</p><p>Access begins after admission.</p><p>Removal is ordinary membership removal.</p><button class="full" type="button" data-act="alice">${room().alice?"Remove Alice":"Admit Alice"}</button></div>`;
  if (S.overlay === "people") return inspectHtml(r);
  if (S.overlay === "notices") return S.notices.length ? S.notices.slice(0,20).map(n=>`<div class="hit"><span class="k">${esc(n.at)}</span><div>${esc(n.text)}</div></div>`).join("") : `<p class="tiny">Quiet.</p>`;
  if (S.overlay === "admin") return `<p class="lede">S-18 exists over the wire. This is the missing screen.</p>${(r.members||[]).map(id => { const p = person(id); if (!p) return ""; return `<div class="listbtn"><span class="avatar">${esc(p.initials)}</span><span style="flex:1">${esc(p.name)}</span>${id!=="me"?`<button class="tiny danger" type="button" data-act="kick" data-arg="${id}">Remove</button>`:""}</div>`; }).join("")}<button class="full" type="button" data-act="invite" style="margin-top:12px">Copy invite link</button><button class="full" type="button" data-act="export" style="background:var(--raised);color:var(--fg);margin-top:8px">Export transcript</button>`;
  return "";
}
function specView() { const tabs = [["features","Features"],["pages","Pages"],["feasibility","Feasibility"],["roadmap","Roadmap"]]; let body = ""; if (S.spec==="features") body = FEATURES.map(([id,name,st,note]) => `<div class="rowitem"><div class="t"><span>${esc(name)}</span><span class="mono">${id}</span></div><p class="tiny ${st==="shipped"?"ok":st==="hygiene"||st==="stub"?"warn":"acc"}">${st}</p><p class="tiny">${esc(note)}</p></div>`).join(""); else if (S.spec==="pages") body = [["Room","/","The object"],["Inbox","/ · list","Conversations"],["Thread","/ · thread","Bubbles"],["Inspector","/ · people","Members"],["Admin","overlay","Owner tools"]].map(([n,p,d])=>`<div class="rowitem"><div class="t">${esc(n)}</div><p class="mono">${esc(p)}</p><p class="tiny">${esc(d)}</p></div>`).join(""); else if (S.spec==="feasibility") body = `<p class="lede">The current repository can become a daily-usable messenger in weeks. It cannot become the iPhone of private rooms without a second architecture.</p><div class="block"><p class="tiny">Messaging core</p><div class="bar"><i style="width:80%"></i></div></div><div class="block"><p class="tiny">Calls</p><div class="bar"><i style="width:10%"></i></div></div><div class="block"><p class="tiny">Encryption</p><div class="bar"><i style="width:20%"></i></div></div>`; else body = `<h3 style="font-family:var(--display);font-weight:500">Fixes</h3>${FIXES.map(([id,t,d])=>`<div class="rowitem"><div class="t"><span class="mono">${id}</span> ${esc(t)}</div><p class="tiny">${esc(d)}</p></div>`).join("")}<h3 style="font-family:var(--display);font-weight:500">Blockers</h3>${BLOCKERS.map(([id,t,d])=>`<div class="rowitem"><div class="t"><span class="mono">${id}</span> ${esc(t)}</div><p class="tiny">${esc(d)}</p></div>`).join("")}`;
  return `<header class="th"><button class="icon" type="button" data-act="roomview" aria-label="Back">${ico("back")}</button><div class="brand" style="font-size:18px">${MARK} Spec</div></header><div class="spec"><div class="spec-in"><nav>${tabs.map(([id,l])=>`<a href="#/spec/${id}" class="${S.spec===id?"on":""}" data-act="sect" data-arg="${id}">${l}</a>`).join("")}</nav><article><h1>${tabs.find(t=>t[0]===S.spec)?.[1]||"Spec"}</h1><p class="lede">Scored against Alice Chains — not the brochure.</p>${body}</article></div></div>`; }
function ico(name) { const p = { plus:"M12 5v14M5 12h14", gear:"M12 15a3 3 0 1 0 0-6 3 3 0 0 0 0 6z", search:"M11 19a8 8 0 1 1 0-16 8 8 0 0 1 0 16zM21 21l-4.3-4.3", file:"M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8zM14 2v6h6", phone:"M22 16.9v3a2 2 0 0 1-2.2 2 19.8 19.8 0 0 1-8.6-3.1 19.5 19.5 0 0 1-6-6A19.8 19.8 0 0 1 2.1 4.2 2 2 0 0 1 4.1 2h3a2 2 0 0 1 2 1.7c.1.9.3 1.8.6 2.6a2 2 0 0 1-.4 2.1L8.1 9.9a16 16 0 0 0 6 6l1.5-1.2a2 2 0 0 1 2.1-.4c.8.3 1.7.5 2.6.6a2 2 0 0 1 1.7 2.1z", users:"M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8z", back:"M19 12H5M12 19l-7-7 7-7", clip:"M21.4 11.6l-9.2 9.2a6 6 0 1 1-8.5-8.5l9.2-9.2a4 4 0 0 1 5.7 5.7L9.5 18.1a2 2 0 1 1-2.8-2.8l8.5-8.4", mic:"M12 1a3 3 0 0 1 3 3v8a3 3 0 0 1-6 0V4a3 3 0 0 1 3-3zM19 10v2a7 7 0 0 1-14 0v-2M12 19v4", video:"M23 7l-7 5 7 5V7zM14 5H3a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h11a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2z", bell:"M18 8A6 6 0 0 0 6 8c0 7-3 9-3 9h18s-3-2-3-9M13.7 21a2 2 0 0 1-3.4 0" }[name] || "M5 12h14"; return `<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="${p}"/></svg>`; }
let callTimer = null;
function bind() { document.querySelectorAll("[data-act]").forEach(el => { el.addEventListener("click", ev => { ev.stopPropagation(); act(el.getAttribute("data-act"), el.getAttribute("data-arg")); }); }); const draft = document.getElementById("draft"); if (draft) { draft.addEventListener("input", e => { S.draft = e.target.value; const c=document.querySelector(".count"); if(c) c.textContent=`${S.draft.length}/${CAP}`; const b=document.querySelector(".send"); if(b) b.disabled=!S.draft.trim(); }); draft.addEventListener("keydown", e => { if (e.key==="Enter" && !e.shiftKey) { e.preventDefault(); send(); } }); } const q = document.getElementById("q"); if (q) q.addEventListener("input", e => { S.query = e.target.value; render(); document.getElementById("q")?.focus(); }); }
function act(name, arg) {
  if (name==="room") return setRoom(arg);
  if (name==="back") { S.mobile="list"; render(); return; }
  if (name==="overlay") { S.overlay = arg; render(); return; }
  if (name==="close") { S.overlay=null; render(); return; }
  if (name==="send") return send();
  if (name==="attach") return send("brief.pdf","file");
  if (name==="voice") return send("Voice note · 0:04","voice");
  if (name==="reply") { S.replyTo = arg; render(); document.getElementById("draft")?.focus(); return; }
  if (name==="noreply") { S.replyTo=null; render(); return; }
  if (name==="react") return react(arg);
  if (name==="del") return delMsg(arg);
  if (name==="edit") { S.editing = arg; render(); return; }
  if (name==="canceledit") { S.editing=null; render(); return; }
  if (name==="saveedit") return saveEdit(arg, document.getElementById("editbox")?.value||"");
  if (name==="call") { S.overlay="call"; S.calling=true; S.elapsed=0; if(callTimer) clearInterval(callTimer); callTimer=setInterval(()=>{ if(!S.calling) return; S.elapsed++; render(); },1000); render(); return; }
  if (name==="endcall") { S.overlay=null; S.calling=false; S.muted=false; if(callTimer) clearInterval(callTimer); render(); return; }
  if (name==="mic") { S.muted=!S.muted; render(); return; }
  if (name==="dm") return openDm(arg);
  if (name==="block") { S.blocked.push(arg); S.rooms=S.rooms.filter(r=>r.id!==arg); persist(); render(); return; }
  if (name==="newgroup") { const id="west"; if (!S.rooms.find(r=>r.id===id)) S.rooms.unshift({ id, name:"Studio West", kind:"group", preview:"New group", time:"Now", unread:0, encrypted:true, alice:false, muted:false, members:["me","nara","lev"] }); setRoom(id); return; }
  if (name==="mute") { S.rooms=S.rooms.map(r=>r.id===S.roomId?{...r,muted:!r.muted}:r); persist(); render(); return; }
  if (name==="alice") return toggleAlice();
  if (name==="spec") { S.view="spec"; persist(); location.hash="#/spec/"+S.spec; render(); return; }
  if (name==="sect") { S.spec=arg; persist(); location.hash="#/spec/"+arg; render(); return; }
  if (name==="roomview") { S.view="room"; persist(); location.hash="#/"; render(); return; }
  if (name==="older") { S.pageOffset[S.roomId]=(S.pageOffset[S.roomId]||0)+PAGE; persist(); render(); return; }
  if (name==="offline") { S.offline=true; persist(); render(); return; }
  if (name==="online") { S.offline=false; persist(); flushOutbox(); render(); return; }
  if (name==="saveprofile") { S.profile.name = document.getElementById("pname")?.value || S.profile.name; S.profile.status = document.getElementById("pstat")?.value || S.profile.status; persist(); S.overlay=null; render(); return; }
  if (name==="export") { const text = threadAll().map(m => `[${m.at}] ${person(m.authorId)?.name||m.authorId}: ${m.text}`).join("\n"); const a = document.createElement("a"); a.href=URL.createObjectURL(new Blob([text],{type:"text/plain"})); a.download=`alisons-${S.roomId}.txt`; a.click(); return; }
  if (name==="invite") { navigator.clipboard?.writeText(`alisons://join/${S.roomId}`); S.notices.unshift({id:"inv"+Date.now(), text:"Invite copied", at:clock()}); persist(); render(); return; }
  if (name==="kick") { S.rooms = S.rooms.map(r => r.id!==S.roomId?r:{...r, members:r.members.filter(id=>id!==arg)}); S.messages.push({ id:"k"+Date.now(), convId:S.roomId, authorId:"system", text:`${person(arg)?.name||arg} removed`, at:clock(), kind:"system" }); persist(); render(); return; }
  if (name==="reset") { localStorage.removeItem(KEY); Object.assign(S, { ...defaults(), draft:"", overlay:null, mobile:"list" }); render(); return; }
}
window.addEventListener("keydown", e => { if (e.key==="Escape" && S.overlay) { S.overlay=null; render(); } });
window.addEventListener("hashchange", () => { const h = location.hash.replace(/^#\/?/,""); if (h.startsWith("spec")) { S.view="spec"; S.spec=h.split("/")[1]||"features"; render(); } else if (h==="" || h==="/") { S.view="room"; render(); } });
if (location.hash.startsWith("#/spec")) { S.view="spec"; S.spec=location.hash.split("/")[2]||"features"; }
render();
